### ISSUE TITLE
Inform about enabling the update mode on the device

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-update-tool#1]
Show this message on tool's start:
```
This tool allows to update Nitrokey Storage's firmware. Please select
<I>Configure -> Enable Firmware Update</I> in the Nitrokey App [2] and
download the .hex file of the latest firmware version[1].

[1] https://github.com/Nitrokey/nitrokey-storage-firmware/releases/latest
[2] https://www.nitrokey.com/download
```

**Comment by szszszsz** [comment]
Fixed with https://github.com/Nitrokey/nitrokey-update-tool/commit/e404bf232c40e65f228389b6c27e1a37fb95400c. 
Current screen shot:
![screenshot from 2018-06-12 19-33-55](https://user-images.githubusercontent.com/17005426/41306836-a87ad960-6e77-11e8-9806-2e2b293e04d2.png)

**Comment by szszszsz** [comment]
Additionally tool's closing is not possible while the update procedure is running.

**Comment by jans23** [comment]
1. I tried the 0.4 release under Windows and the instructions are not displayed. Here is how it looks for me:
![screenshot](https://user-images.githubusercontent.com/1450547/41313903-75609b50-6e8b-11e8-896c-ced380bcd986.png)
2. I suggest to remove the first four lines (NK Prod tool started... Source is available...) because it distracts users from reading the actual instructions (if displayed as desired)
3. Please change the text "Device connected in update mode: false" to "Nitrokey Storage detected. Please enable firmware update mode in Nitrokey App first."

**Comment by szszszsz** [comment]
Sorry for not directly mentioning - #1 fix will be released in v0.5 (v0.4 is not containing it). I will apply the rest of the suggestions.

**Comment by szszszsz** [comment]
Current view:
![screenshot from 2018-06-13 09-43-19](https://user-images.githubusercontent.com/17005426/41337091-8924ccca-6eee-11e8-9cda-7b5a7b0568c8.png)

**Comment by jans23** [comment]
Screenshot looks much better. 

What does "see Links..." mean? I don't think it is clear to users where
to look. Perhaps adding the link right there instead?

I suggest to replace bullet points with numbers (1, 2, 3, 4) to make it
more clear that these are steps.

>

**Comment by szszszsz** [comment]
OK! Will be changed to numbers.

I have added a `Links` submenu to the application, whose items are opening the required URLs. I will add `menu` word to the description to indicate that better. If that would still not be obvious, I will add the URLs in the text as suggested.
